sc-forks/solidity-coverage

- README.md
+ repo name
+ add options
+ list contributors
+ add contribution guidellines
+ warn about accuracy
> Edit readme 

- package.json
+ This is temporary, pending npm publication of recent changes to SP.
+ SP uses `prepublish` to build the parser and can't be installed as a dep from its git repo.
> Pin solidity-parser to sc-forks#master 

- bin/exec.js
- lib/parse.js
- test/cli.js
- test/util/mockTruffle.js
+ Includes a unit test for the coverage network declarations - unfortunately this is one that has to be verified manually by seeing what port is logged while coverage runs. Also disabled for CI because of the container memory limit issue.
> Use coverage network port if available

- .gitignore
- bin/exec.js
- lib/coverageMap.js
Part one of #9. Writes topic hashes to a file that testrpc can load and filter against. Also removes this meta data file on program close.
> Add topic logging to coverageMap

- bin/exec.js
> Stop crashing on encounters with non-truffle projects

- README.md
- bin/exec.js
- test/cli.js
The exception is `node_modules`, which must have copyNodeModules
set to `true` in `.solcover.js` in order to be included.
Fixes #39. I'm not sure what you want to see in terms of #43, though.
EDIT: I seem to have clobbered a load of trailing spaces in this PR too. Maybe it's best to just bin this PR 😛 .
> Copy all directories when setting up coverageEnv

- README.md
- bin/exec.js
Resolves #42.
Kind of copped out here but basically - if you're passing in a testrpc options string, you should specify a port there, & also set the .solcover.js port option, and your coverage network port should not conflict with these settings. Otherwise tool will break.
> Small exec.js cleanup, clarify port options settings in README

- bin/exec.js
Verified that it runs without issue on zeppelin (which installs it own testrpc too). Resolves #45
> Change testrpc path for yarn compatibility

- README.md
- bin/exec.js
- test/cli.js
While ordinarily we shouldn't want to do this, it is possible to construct valid contracts using assembly that break when the coverage events are injected.
An example of such a contract is the [EtherRouter](https://github.com/ownage-ltd/ether-router/blob/master/contracts/EtherRouter.sol) contract by Peter Borah. It repeatedly calls `mload(0x40)` when it needs a memory address, as it only uses one piece of memory at a time and repeatedly overwrites the memory starting at the address contained in `0x40`. In Solidity, `0x40` is a special memory address that contains the address of the first empty slot. When events in solidity are compiled, they use the address contained in `0x40` and update it, and so the injected instrumentation events clobber the memory that `EtherRouter` is using.
This …
> Allow files to be skipped during coverage

- README.md
- package.json
I'm holding off on merging this because I removed the migrations.js `require` warning from the README assuming 3.3.1 fixed everything but it seems to [still be a problem](https://github.com/sc-forks/solidity-coverage/issues/39#issuecomment-312121640).  Will revisit tomorrow.
> Add gasEstimation example. Pin dev Truffle to 3.2.5 for now.

- lib/instrumenter.js
- lib/parse.js
- test/conditional.js
- test/sources/conditional/mapping-assignment.sol
+ Resolves #54
+ Adds a coverage unit test for this case.
+ NB: solution implemented here is, frankly, of questionable safety. It involves slightly modifying the start position of the `AssignmentExpression` before injecting the statement event so that we can later wrap the `MemberExpression` as a tuple correctly. It's conceivable that something before the `AssignmentExpression` will get mangled. Also not sure highlighting will be right here. 
This probably needs another commit before merging to deal with these qualms.
> Instrument conditional assignment to MemberExpressions

- lib/parse.js
- test/sources/statements/empty-contract-ala-melonport.sol
- test/statements.js
Slightly modifies the `ContractStatement` injection so that it can handle case where there is no whitespace between the opening and closing brackets of an empty contract declaration.  Adds a test.
> Instrument empty contract bodies correctly

- README.md
> README updates: remove require info, add memory info

- package.json
This is to provide a safe-haven we can revert to on npm while testrpc-sc is upgraded to v.4
> Pin testrpc-sc to the 3.0.3 branch

- docs/testrpc-sc.md
- lib/app.js
- package.json
Resolves #64 
+ Includes the beginnings of a [guide to testrpc-sc publication / modification](https://github.com/sc-forks/solidity-coverage/blob/master/docs/testrpc-sc.md)
+ Upgrades to our own published version of [4.0.1](https://www.npmjs.com/package/ethereumjs-testrpc-sc)
+ Adds dependencies we were getting as part of the old testrpc including web3@^0.18.4
+ Changes the `node_modules` path we launch testrpc with as part of yarn compatibility, since that changed in v4.
In the end I decided to keep testrpc-sc `master` as it is and publish v4 from a `coverage` branch. In a month or something we could deprecate current master and start syncing it with its upstream parent. Then we can make the default branch `coverage`, periodically merging upstream changes into it.  Or whatever . . . once …
> Upgrade to ethereumjs-testrpc-4.0.1

- lib/instrumenter.js
- test/comments.js
- test/sources/comments/postContractComment.sol
- test/sources/comments/postFunctionDeclarationComment.sol
- test/sources/comments/postIfStatementComment.sol
- test/sources/comments/postLineComment.sol
Fix the off-by-one-error discovered with comments immediately following function declarations. Also added tests to check that we didn't have similar issues with other statements / declarations.
Fixes #88
> Correctly instrument comments near function's {

- lib/app.js
- test/app.js
- test/util/mockTruffle.js
Resolves #93.
+ Checks for existence of alternate truffle.js named `truffle-config.js` (windows issue).
+ Names stub truffle config file `truffle-config.js` when platform is windows. 
+ Adds test for alternate file name.
> Allow truffle.js to be named truffle-config.js

- .eslintrc
- circle.yml
- package-lock.json
- package.json
- test/app.js
- test/cli/wallet.js
- test/sources/cli/Wallet.sol
This PR adds a unit test to validate a fix in `ethereumjs-vm-sc` for the transfer / send bug discovered in #106.  ~Test is skipped because it will fail pending the vm change.~
@area I wrote this using await/async and I've bumped the `circle.yml` and `eslint` up to Node 7. If this is troubling (irritating?) - let me know.  I'll revert without complaint. 🙂  
It's nice for our tests but we probably shouldn't use any V7 features in the tool itself until truffle and/or testrpc make the same move.   
Requesting a review from you re: node.
> Add transfer / send unit test. Use Node7

- bin/exec.js
Fixes a failure to register the sigint handler before we generate the `coverageEnv` and instrument the project.  People who hit `ctrl-c` during that phase of the run were left with debris in the repo which confused subsequent runs of the tool.
Resolves #113.
Thanks @nberger for description and solution.
> Register sigint handler immediately

- README.md
- docs/faq.md
- package.json
- test/app.js
Resolves #118 at the cost of re-opening #106. 
Stipend is free and you can't just make it 230000 - calling accounts will get refunded gas that was never debited from them. Bumping `testrpc-sc` down to pre-stipend version and adding some notes to the docs.
> Revert vm stipend fix

- lib/app.js
- test/assert.js
- test/comments.js
- test/conditional.js
- test/expressions.js
- test/function.js
- test/if.js
- test/loops.js
- test/statements.js
Bug fix for handling Windows paths.
I tried to limit the impact of this change on any other platforms.  Many of the unit tests fail on Windows (even without this change) probably due to a similar path handling issue.  
Please verify on other platforms that there is no negative impact.  
Fix for #112
> Bug fix for handling Windows paths

- lib/app.js
Resolves bug reported and fixed by @rudolfix at #120. All credit to them. 
Without this large test suites will max out the stdout buffer using the internally launced testrpc.
> Increase testrpc-sc stdout buffer size

- lib/preprocessor.js
- package-lock.json
- package.json
- test/app.js
- test/cli/pureview.js
- test/sources/cli/PureView.sol
Some upgrades for new language features:
+ Bumps truffle and solc deps / removes unused deps
+ upgraded the parser to accept experimental pragmas
+ patched vm by pinning ethereumjs-block (fork is coming soon)
+ globally replacing all occurrences of `pure` and `view` with a single space in the preprocessing step.
+ adds a test for aforementioned modifiers
re: pure/view, obviously opted for the absolute cheapest patch. People disadvantaged by this approach will be all who use the words pure or view in quotes. 
Otherwise believe this is ok b/c:
+ pure and view appear to be keywords / can't be variable names.
+ we're already changing everything's position in preprocessing so alignments might stay tight.
Closes #16 
Closes #131 
Closes #128
> Permit view, pure, experimental and solc 0.4.17

- docs/testrpc-sc.md
- lib/instrumentSolidity.js
- lib/preprocessor.js
- package-lock.json
- package.json
Tried to use `solparse` but there was a failing test that looked like it was caused by a discrepancy in whitespace handling at some rule? Or maybe start/end pos. 
Now more yarn compatible. 
#128
> npm publishing solidity-parser-sc

- lib/app.js
- package-lock.json
- package.json
- test/sources/cli/PureView.sol
- test/sources/cli/TotallyPure.sol
Somewhat belatedly realised that stripping off these modifiers changes their behavior. Constant / View and Pure return values not transaction objects. 
We're really getting squeezed into a corner here, EOL.
> Do not preprocess view and constant

- lib/app.js
- test/app.js
- test/cli/totallyPure.js
Just a PR to trigger a build and demonstrate that this fix to #146 works.
> Restore preprocessing of constant/view

- lib/app.js
- lib/preprocessor.js
- test/app.js
- test/sources/cli/CLibrary.sol
- test/sources/cli/TotallyPure.sol
- test/util/mockTruffle.js
Uses the preprocessor walking over the AST rather than a regex.
~Not mergeable -~ I want to do a test to show that this fixes #153, but wanted to see if this broke anything else in the tests, to begin with.
> Only remove pure/view/constant from functions

- lib/app.js
- lib/preprocessor.js
- test/util/mockTruffle.js
I introduced a nice bug in #147 which this fixes. In order to remove `constant` from all functions for instrumentation to take place, including those imported from `./node_modules`, I ran the (increasingly badly named...) preprocessor over all `.sol` files that we find in the tree. Unfortunately, if we're using `copyNodeModules:true`, then that includes the `solidity-coverage` repository, which includes [SimpleError.sol](https://github.com/sc-forks/solidity-coverage/blob/4c2c9e5e994d44cda3fb39f0359f06a8531ebf88/test/sources/cli/SimpleError.sol), which deliberately has a syntax error in it! This caused an uncaught error to be thrown, and `solidity-coverage` to fail to run.
I did think about just skipping `SimpleError.sol` itself, but don't want to be in the position where we break if any …
> Handle *.sol files that are invalid Solidity

- README.md
- lib/app.js
Added a new config var `copyPackages` to specify which packages to copy from node_modules.
This is really useful for larger projects since copying the whole content of `node_modules` makes `solidity-coverage` consume tons of resources and take a lot of time to complete.
> Significantly improves coverage time, specially for large projects.

- lib/app.js
Apparently, one could use `build/something` to store autogenerated code. Upstream removes that all together. Proposed pull request narrows the scope of a cleaning operation to the truffle-generated files only.
> Remove only build/contracts

- package-lock.json
- package.json
- test/sources/statements/fn-struct.sol
- test/statements.js
Found by @stuarth1. PR bumps parser, adds a regression test for this case.
```javascript
struct S {
function(bytes32) internal constant returns(bool) startConditions;
}
```
> Fix parsing bug preventing fn definition in structs

- lib/instrumenter.js
- test/comments.js
The test for comments after a line just checked that the contracts compiled, not that they were instrumented correctly. It transpires that if a comment was placed on a line, then that line was not included in the line coverage date (though branch coverage etc. was all fine). While branch coverage is the best metric to use, we should make all our metrics correct!
This PR accommodates only lines that have comments with the `//` syntax, which I would expect to be the most common comment style (i.e. I would expect that starting a multiline comment at the end of a line would be unusual; the same for natspec comments). Stripping comments in general requires proper parser support, and I don't think our parser provides us with that information?
> Include lines with comments in line coverage

- lib/app.js
- package-lock.json
- package.json
Uses the new stable ganache-core. Did not update the `vm`, but this might be necessary because a few small things have changed there since Byzantium. . . .
> Bump testrpc-sc to 6.1.0

- lib/app.js
Since `--gasLimit` is added to `testrpcOptions` the left-side of the `||` expression is always true.
> Fix rpc server launch

- package.json
Updates testrpc-sc to use the latest `ganache-cli`. Tried to take a shortcut in #203 by only updating `ganache-core`, incorrectly.
> Update testrpc-sc to 6.1.2

- lib/injector.js
- lib/instrumenter.js
- package-lock.json
- package.json
- test/conditional.js
- test/sources/cli/Face.sol
- test/sources/cli/PureView.sol
- test/sources/cli/TotallyPure.sol
+ Prefixes coverage events with `emit`. This will become mandatory with solc 0.5.0. 
+ solc to 0.4.21
+ truffle to 4.1.5
PR is a breaking change because the `emit` keyword isn't recognized by older solc versions. Additionally, `solc` is refusing to allow emit to be used within the `conditional` instrumentation tuple so conditionals instrumentation has been turned off. Tried wrapping it in some additional parens but no luck. Not sure what to do about this.....
```javascript
uint z = (x) ? 1 :  2;  // Now instrumented as mere statement.
```
> Emit coverage events. 

- lib/parse.js
- package-lock.json
- package.json
- test/function.js
- test/sources/function/constructor-keyword.sol
- test/sources/statements/emit-coverage.sol
- test/sources/statements/emit-instrument.sol
- test/statements.js
+ `solidity-parser-sc` to 0.4.8
+ `solc` dev dep to 0.4.23
+ `truffle` dev dep to 4.1.7
+ Instrument `emit` statements correctly. 
+ Allow use of the constructor keyword
Addresses #213, #213, #220,
> Upgrades to support `emit` and `constructor`

- package-lock.json
- package.json
Fixes #227. `solidity-parser-sc` had an older mocha dependency that triggers `audit` warnings.
> Upgrade solidity-parser-sc to 0.4.9

- lib/app.js
To be honest, I don't know if this is the best way of doing it...
Getting the path of testrpc dynamically enables solcover to work in mono repos when packages get hoisted to the root directory.
> Use require.resolve() to get the path of testrpc-sc

- docs/testrpc-sc.md
- package-lock.json
- package.json
Upgrades to testrpc-sc  @area synced to newer ganache-cli (which has reason strings etc). Also behaves slightly differently when executing a `revert` in a `view` fn but this is a bug fix.
> Upgrade testrpc-sc to 6.1.6, add doc notes

- lib/app.js
#238
add check to honor the excluded files in `view` and `pure` modifiers processing functionality.
(cherry picked from commit 476dc4d95ce8a69a4d5eda03911efb1391b9005c)
This should make it possible to instrument projects that use Oraclize, as long as the Oraclize contracts are skipped.
> Honor excluded files

- lib/app.js
Reverts sc-forks/solidity-coverage#274
It turns out that this might be problematic, zeppelin's mocks aren't compiling....
`TypeError: Overriding function changes state mutability from "nonpayable" to "view".`
```
/Users/cgewecke/code/sc-forks/zeppelin-solidity/coverageEnv/contracts/mocks/SafeERC20Helper.sol:28:3: TypeError: Overriding function changes state mutability from "nonpayable" to "view".
function allowance(address, address) public constant returns (uint256) {
^ (Relevant source part starts here and spans across multiple lines).
/Users/cgewecke/code/sc-forks/zeppelin-solidity/coverageEnv/contracts/token/ERC20/ERC20.sol:17:3: Overriden function is here:
function allowance(address owner, address spender) public  returns (uint256); …
```
> Revert "Honor excluded files"

- lib/app.js
Previously, `postProcessPure(env)` would re-instrument any files that were already instrumented by `instrumentTarget()`. As the instrumentation is quite expensive, this usually doubled the building time for the tests (on one codebase, the overhead before any test was run decreased from 150s to 90s).
> Avoid instrumenting entire codebase twice

- README.md
- lib/app.js
This option allows you to skip post-processing for skipped files. Growing number of problems with files like Oraclize that are huge, weirdly formatted, and make the instrumentation hang.
Unfortunately this doesn't work for cases like Zeppelins which has skipped mock contracts that don't belong in the report but do need post-processing.
> Add deep skip option

- lib/app.js
Fixes https://github.com/sc-forks/solidity-coverage/issues/289
Added node in-front of the command being executed by childprocess.exec(). This will make sure that windows will execute the js file rather than opening it in a text editor.
> Added 'node' to a command

- README.md
README.md references zeppelin-solidity which was renamed to openzeppelin-solidity quite a while ago.
> openzeppelin-solidity rename in README

- .circleci/config.yml
- scripts/run-colony.sh
- scripts/run-zeppelin.sh
These scripts:
+  clone a large production project (OpenZeppelin, ColonyNetwork)
+  install PR candidate branch on it
+ run coverage.
(This was kind of a deep dive in CircleCI quirks. Everything needs to run with sudo, sudo invoked shell scripts don't share the container's env variables, can't run a docker command inside a script, etc.)
Zeppelin has their own testrpc-sc fork which includes a new feature that emits free logs. This makes it possible to test contracts which gas check w/in solidity.
> Add E2E CI tests

- package.json
- test/app.js
- yarn.lock
Makes `emitFreeLogs` truly free and fixes #106 (finally). 
Should also resolve the test failures in [aragon-os 541](https://github.com/aragon/aragonOS/pull/541)
> Upgrade testrpc-sc 6.4.5-sc.3

- package.json
- test/sources/statements/type-keyword.sol
- test/statements.js
- yarn.lock
#348 
Support for the `type` keyword was added 10 days ago at parser-antlr [here](https://github.com/solidityj/solidity-antlr4/commit/b7065ca7a2d00662b345f2fdd2940d00d51ad30d) but the parser was pinned to `0.4.5`, (because of a bug in `0.4.6`)
**Notes**
+ restoring the caret on the parser dep. 
+ adding regression test w/ source provided by @seita-uc
> Update solidity-parser-antlr to ^0.4.7 (type keyword)

- .circleci/config.yml
- scripts/run-metacoin.sh
- scripts/run-zeppelin.sh
+ Moves all E2E tests into script files and runs Zeppelin / Metacoin on `machine` with nvm (instead of docker)
+ Add logic to pull the correct branch for E2E when running PR from a fork (continuation of #366 - needs to be tested)
> Fix CI for forks

- lib/collector.js
- lib/injector.js
- lib/parse.js
- package.json
- test/sources/solidity/contracts/statements/stack-too-deep.sol
- test/units/statements.js
- yarn.lock
Modifies the instrumentation strategy to use a function call with the instrumentation hash as an argument. This provides a way of getting around 'stack-too-deep' compiler errors which seem more common than initially anticipated. (An initial test on [aragon-court](https://github.com/aragon/aragon-court/blob/development/contracts/Court.sol) triggered many of these.
Instrumentation now looks something like...
```solidity
contract Test {
// Hex identifier postfixes are hashes of the filename 
function coverage_0xab123(bytes32 c__0xab123) public pure {}
function a(uint x) public {
coverage_0xab123(0xdc08f...08ed1); /* function */ 
coverage_0xab123(0xa9065...549e2); /* line */         
coverage_0xab123(0x6ac83...f2037); /* statement */ 
if (x == 1) {
coverage_0xab123(0x85e7e...afacf); /* branch …
```
> Instrument with injected function calls 

- lib/parse.js
- test/sources/solidity/contracts/statements/interface.sol
- test/units/statements.js
Instrumenting interfaces triggers an error like this:
```
,/contracts/standards/ERC900.sol:6:1: TypeError: Functions in interfaces cannot have an implementation.
function coverage_0xdcb93d1c(bytes32 c__0xdcb93d1c) public pure {}
^----------------------------------------------------------------^
,/contracts/standards/ERC900.sol:6:1: TypeError: Functions in interfaces must be declared external.
function coverage_0xdcb93d1c(bytes32 c__0xdcb93d1c) public pure {}
^----------------------------------------------------------------^
```
Also adds interface test
> Stop injecting coverage hash fn definition in interfaces

- dist/truffle.plugin.js
- lib/app.js
- test/units/app.js
Fixes bug where importing contracts from outside the contracts directory using a relative path failed under coverage. Changes the temp folder format from
```
.coverageEnv / 
contracts /
build /
contracts /
```
...to 
```
.coverage_contracts /
.coverage_artifacts /
contracts /
```
> Create separate contract & artifact temp folders at root

- README.md
- lib/app.js
- test/integration/projects/import-paths/.solcover.js
- test/integration/projects/multiple-migrations/.solcover.js
- test/integration/projects/skipping/.solcover.js
- test/integration/projects/test-files/.solcover.js
- test/units/app.js
Ports #308 to the `0.7.0` work, adding an `istanbulReporter` option.
**Example**
```
istanbulReporter: ['json-summary']
```
[List of available reporters](https://istanbul.js.org/docs/advanced/alternative-reporters/)
Adds coverage expectation fixtures to the plugin tests and starts using the json-summary reporter to test percentages.
> Istanbul reporter

- dist/truffle.plugin.js
- lib/ui.js
- test/units/app.js
- test/util/integration.truffle.js
```
Usage: truffle run coverage [options]
Options: 
--solcoverjs: relative path to .solcover.js (ex: ./../.solcover.js
--file: path (or glob) to run subset of JS test files
--help: help
```
Using `--solcoverjs` in lieu of `--config` because we're subordinate to the plugin APIs and would like to avoid any name conflicts in future...
> Add --solcoverjs and --help command options

- dist/truffle.plugin.js
- lib/app.js
- lib/ui.js
- test/units/app.js
Adds logic to use an in-process ganache supplied by the dev platform's plugin API, falling back on ganache-core-sc (2.7.0) if that fails. 
Because there is [no official API](https://github.com/trufflesuite/ganache-core/issues/464) at ganache yet exposing the vm step and because the vm is instantiated at ganache core launch *and* every time an eth_call is made, we attach in kind of a complicated (brittle?) way:
+ monkey-patched around `blockchain_double.createVMFromStateTrie` (eth_call)
+ attached to `provider.engine.manager.state.blockchain` (eth_send)
> Attach to non-fork ganache vm

- dist/truffle.plugin.js
- test/integration/projects/multiple-migrations/.solcover.js
- test/integration/projects/multiple-migrations/test/contracta.js
- test/integration/projects/multiple-migrations/test/contractb.js
- test/units/truffle/errors.js
- test/units/truffle/flags.js
- test/units/truffle/standard.js
- test/util/integration.truffle.js
- test/util/verifiers.js
Lets you write tests with a grep-able tag... 
```javascript
it("is a gas usage simulation [ @fails-coverage ]", async function(){
//...
});
```
...and skip them via solcoverjs
```javascript
module.exports = {
mocha: {
grep: "@fails-coverage",
invert: true
}
}
```
(PR also has some additional tests cleanup).
> Add mocha options to solcoverjs

- .circleci/config.yml
- dist/plugin-assets/truffle.ui.js
- dist/truffle.plugin.js
- lib/app.js
- lib/collector.js
- lib/ui.js
- package.json
- scripts/run-zeppelin.sh
- test/units/truffle/errors.js
- test/units/truffle/flags.js
- test/units/truffle/standard.js
- yarn.lock
Begins using ganache.server (instead of provider) so other processes can connect to the coverage run. This should make it possible to use the Oraclize/Provable testing client, as well as simplify Zeppelin's installation of 0.7.0. (See [OZ 1918](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/1918))  
+ Also adds support for `--network <name>` cli flag and tests for all the edge cases introduced by that. 
+ Seems to take ~10 minutes off the zeppelin run (2nd time have seen this), suggesting that there is a big perf difference between the docker (zeppelin's CI) and linux environments (CircleCI machine) for provider.
> Use ganache server (instead of provider)

- lib/app.js
- lib/ui.js
- lib/validator.js
- package.json
- test/units/truffle/errors.js
- test/units/validator.js
- yarn.lock
Includes checks for to-be-implemented sequence hooks (functions):
```
onServerReady
onTestsComplete
onIstanbulComplete
```
> Validate solcoverjs options with json-schema

- dist/bin.js
- lib/ui.js
- package.json
- test/units/truffle/errors.js
- yarn.lock
Ex:
```
$ testrpc-sc
```
```
$ solidity-coverage
```
> Add warnings for deprecated shell commands

- README.md
- dist/truffle.plugin.js
- lib/api.js
- test/integration/projects/test-files/.solcover.js
- test/units/truffle/standard.js
These allow you to run preparatory scripts which require the ganache server before executing the tests. Launching the Oraclize/Provable is an example use-case. Terminal hooks allow you to clean resources up or post-process generated artifacts.
These hooks are meant to mitigate some of the problems raised by having an in-process client which cannot be launched separately at the command line. See [openzeppelin 1918](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/1918)
> Add onServerReady, onTestsComplete, onIstanbulComplete Hooks

- lib/ui.js
We should use https :) As per discussion in https://github.com/sc-forks/solidity-coverage/pull/405
P.S. My first PR here :D
> chore(lib/ui): make URL https:// prefixed

- README.md
- dist/plugin-assets/truffle.ui.js
- dist/truffle.plugin.js
- lib/api.js
- test/integration/projects/test-files/.solcover.js
- test/units/truffle/standard.js
An async hook which runs after compilation, before the tests. It's passed the re-targeted config. It's necessary for projects like JoinColony which have secondary compilation steps and move some files around right before the tests run. (See their npm script step: [provision:token:contracts](https://github.com/JoinColony/colonyNetwork/blob/develop/package.json#L19))
Also fixes a couple bugs in the UI output and adds an entry for `--network` in the CLI options section of the README
> Add 'onCompileComplete' option

- README.md
- dist/plugin-assets/plugin.utils.js
- test/units/truffle/flags.js
Specifies the name of the folder to write compilation artifacts to. A use case is colonyNetwork where there are complex scripts to set up the tests which consume various pieces of the Truffle artifact. All this logic assumes they exist under`build` (rather than `.coverage_artifacts`).
This folder gets created/deleted and needs to be disposable. The user cannot store meaningful deployment data in it.
> Add --temp command flag

- README.md
We've migrated to Codecov. (It's very good!)
> Change OpenZeppelin coverage report link

- README.md
- dist/plugin-assets/buidler.ui.js
- dist/plugin-assets/buidler.utils.js
- dist/plugin-assets/plugin.utils.js
- lib/api.js
- lib/ui.js
- package.json
- test/integration/projects/ganache-solcoverjs/.gitignore
- test/integration/projects/ganache-solcoverjs/.solcover.js
- test/integration/projects/ganache-solcoverjs/buidler.config.js
- test/integration/projects/ganache-solcoverjs/contracts/ContractA.sol
- test/integration/projects/ganache-solcoverjs/contracts/ContractB.sol
- test/integration/projects/ganache-solcoverjs/contracts/ContractC.sol
- test/integration/projects/ganache-solcoverjs/contracts/Migrations.sol
- test/integration/projects/ganache-solcoverjs/test/contracta.js
- test/integration/projects/ganache-solcoverjs/test/contractb.js
- test/integration/projects/ganache-solcoverjs/test/contractc.js
- test/integration/projects/ganache-solcoverjs/truffle-config.js
- test/units/api.js
- test/units/buidler/flags.js
- test/units/truffle/flags.js
- test/units/truffle/standard.js
- test/util/integration.js
- test/util/util.js
- test/util/verifiers.js
Handful of things to help with test parallelization strategies. It should be possible to distribute the hit map generated during instrumentation to multiple `api.ganache` invocations, as necessary. The folder name istanbul writes coverage reports to should also be configurable so multiple runs can be combined.
+ Refactor api.ganache and test providing client from solcoverjs
+ Add api level setters/getters for instrumentationData 
+ Add `istanbulFolder` option for custom istanbul destinations
+ Add `json` to the list of default reporters
> Prepare API for parallelization 

- README.md
- lib/api.js
- lib/validator.js
- test/units/api.js
- test/units/validator.js
`autoLaunchServer` option added to config and as an optional arg passed to `api.ganache`. When false, `api.ganache` will return the coverage enabled server without calling `listen`, allowing the user to configure that invocation as they wish.
(Added a little config validation clean-up as well)
> Add autoLaunchServer option

- .circleci/config.yml
- package.json
- scripts/run-buidler.sh
- scripts/run-metacoin.sh
- truffle-plugin.json
+ clones [sc-forks/buidler-e2e][1] and installs/runs solidity-coverage at a candidate branch.
[1]: https://github.com/sc-forks/buidler-e2e
> Add simple E2E for Buidler

- .circleci/config.yml
- scripts/run-moloch.sh
Adds MolochVentures/moloch as an E2E (Buidler) target, using the [sc-forks/moloch fork][1] (which is a fork of alcuadrado/moloch. Root repo is not pulling in upgrade PRs & development is breaking the tests on master. 
[1]: https://github.com/sc-forks/moloch
> Moloch E2E

- dist/buidler.plugin.js
- dist/plugin-assets/buidler.utils.js
- dist/truffle.plugin.js
- lib/api.js
- scripts/run-buidler.sh
- scripts/run-moloch.sh
- test/units/buidler/flags.js
- test/units/buidler/standard.js
Also cleaning up a couple small things...
+ Make sure the network requested by `--network` is printed to terminal correctly
+ Only default to config-set ganache when none is provided in the api.ganache invocation.
> Add builder-ethers test to CI

- README.md
- dist/buidler.plugin.js
- test/units/buidler/flags.js
Buidler requires command line params to be lowercase
```
Error BDLR310: Invalid param --testFiles. Command line params must be lowercase.
```
> Stop camel-casing testfiles flag

- api.js
- lib/api.js
- plugins/resources/plugin.utils.js
- test/units/api.js
This...
```javascript
const API = require('solidity-coverage/api');
const api = new API();
const config = {
workingDir: process.cwd(),
contractsDir: path.join(process.cwd(), 'contracts')
artifactsDir: path.join(process.cwd(), 'artifacts')
} 
const {
targets,
skipped, 
} = api.utils.assembleFiles(config)
const instrumented = api.instrument(targets)
```
Also makes `api.report`'s output folder path configurable as an fn argument.
> Export API

- plugins/resources/truffle.utils.js
- test/units/truffle/standard.js
#423
It hangs & its gas data is meaningless here.
> Disable eth-gas-reporter when present in truffle config

- plugins/resources/truffle.utils.js
- test/units/truffle/standard.js
#434 
Handles this case, coercing V4 format optimization to false:
```javascript
module.exports = {
plugins: ["solidity-coverage"],
compilers: {
solc: {
version: "0.5.11"
}
},
solc: {
optimizer: {
enabled: true,
runs: 200
}
}
};
```
> Allow Truffle V4 style solc config

- lib/instrumenter.js
- test/integration/projects/import-paths/contracts/OnlyUsesImports.sol
- test/integration/projects/import-paths/node_modules/package/AnotherImport.sol
> Add imports only test, fix instrumenter

- BUIDLER_README.md
Adds a readme at BUIDLER_README.md which follows the buidler plugin template [guidelines](https://github.com/nomiclabs/buidler-ts-plugin-boilerplate/blob/master/README-TEMPLATE.md#buidler-example-plugin).
> Add buidler readme

- plugins/bin.js
- test/units/truffle/errors.js
The warning added in #405 for `$ solidity-coverage` doesn't work in practice because it's missing a node hash bang. 
See [gnosis/dex-contract comment](https://github.com/gnosis/dex-contracts/pull/436#issuecomment-570512513). 
Should look like:
> Add missing hash bang to .bin warning

- .circleci/config.yml
- package.json
- test/units/truffle/standard.js
- yarn.lock
#475 
+ Ganache to 6.9.0. Keeps pinned (this is a stable backup - users should install their own). 
+ Web3 to 1.2.6 (and remove utils)
+ Use Node 12.16.0 to run E2E tests
+ Use Node 10 to run unit tests (dev deps have their own Node 12 probs)
> Upgrade ganache-cli to 6.9.0 / Web3 to 1.2.6

- lib/instrumenter.js
- lib/preprocessor.js
- package.json
- test/integration/projects/solc-6/buidler.config.js
- test/integration/projects/solc-6/contracts/ContractA.sol
- test/integration/projects/solc-6/test/test.js
- test/integration/projects/solc-6/truffle-config.js
- test/units/buidler/standard.js
- test/units/truffle/standard.js
- yarn.lock
#464 
+ Substitutes solidity-parser-antlr for [solidity-parser-diligence][1]
+ Enable solidity 0.6.2 integrations test (buidler only)
Set up [a parser CI job][3] to sweep across some large contract sets. Zeppelin@dev-v3.0, Synthetix@alpha, and omisego/plasma@master all parse ok. 
However, hit a crash for `payable` as a method in the tests here...
```solidity
function payableFn() public pure {
address x;
address y = payable(x); // Crash
}
```
[1]: https://www.npmjs.com/package/solidity-parser-diligence
[3]: https://app.circleci.com/jobs/github/sc-forks/parser-testing/3
> Parse solc 6.x contracts

- lib/parse.js
- test/sources/solidity/contracts/statements/interpolation.sol
- test/units/statements.js
#478 
```solidity
contract Test is Interpolated("abc{defg}"){
function a(uint x) public {
uint y = x;
}
}
```
> Allow base contract string constructor args with open curly braces

- lib/registrar.js
- test/sources/solidity/contracts/statements/interpolation.sol
- test/units/statements.js
#478 (part II)
```solidity
contract TestB is Interpolated {
constructor(uint x) public Interpolated("abc{defg}") {
uint y = x;
}
}
```
> Allow strings with "{" as modifier arguments

- plugins/truffle.plugin.js
Should fix a problem discovered in [dai-backstop-syndicate 45][1] where test files written in TS are  transpiled to the build folder, 
PR fetches test files immediately before `truffle.test` is run so there's less likelyhood they'll be accidentally overwritten by `truffle.compile`
[1]: https://github.com/backstop-syndicate/dai-backstop-syndicate/pull/45
> Get test files after compileComplete hook runs (Truffle)

- lib/api.js
By allowing `providerOptions.gasLimit` be included in `.solcover.js`, it allows us at Synthetix to avoid these `Exceeds block gas limit` errors, see : https://travis-ci.org/github/Synthetixio/synthetix/jobs/672297483#L2100-L2148. 
> Note: I added support for `allowUnlimitedContractSize` as well cause I was in there and it seemed prudent
> Allowing providerOptions gasLimit and allowUnlimitedContractSize to override defaults

- lib/coverage.js
- lib/injector.js
- lib/instrumenter.js
- lib/parse.js
- lib/registrar.js
- test/integration/projects/logical-or/.solcover.js
- test/integration/projects/logical-or/buidler.config.js
- test/integration/projects/logical-or/contracts/ContractA.sol
- test/integration/projects/logical-or/test/test.js
- test/integration/projects/logical-or/truffle-config.js
- test/sources/solidity/contracts/assert/Require-fn-reason.sol
- test/sources/solidity/contracts/assert/Require-fn.sol
- test/sources/solidity/contracts/or/and-or-brackets.sol
- test/sources/solidity/contracts/or/and-or.sol
- test/sources/solidity/contracts/or/bzx-or.sol
- test/sources/solidity/contracts/or/if-or.sol
- test/sources/solidity/contracts/or/multi-or.sol
- test/sources/solidity/contracts/or/require-multiline-or.sol
- test/sources/solidity/contracts/or/require-or.sol
- test/sources/solidity/contracts/or/return-or.sol
- test/sources/solidity/contracts/or/while-or.sol
- test/sources/solidity/contracts/return/empty-return.sol
- test/sources/solidity/contracts/return/ternary-return.sol
- test/units/assert.js
- test/units/buidler/standard.js
- test/units/expressions.js
- test/units/or.js
- test/units/truffle/standard.js
- test/util/verifiers.js
#175 
Detect and report untaken OR branches..
**TODO**
> Add branch coverage for logical OR conditions 

- BUIDLER_README.md
I was using the solidity-coverage buidler plugin and encountered the issue described in #489.
This PR fixes the installation script in the README by removing "@beta" from the package name, hence installing the latest available version (0.7.5 at the time of writing this).
> docs: fix installation script in buidler readme

- lib/injector.js
- lib/parse.js
- lib/registrar.js
- package.json
- test/integration/projects/solc-6/contracts/ContractA.sol
- test/units/buidler/standard.js
#510 
`solc 0.6.x` is strict about overriding inherited methods. If a file has multiple contracts in it with an inheritance relationship between them, the public instrumentation method declared at the top of each must be unique per contract. 
Prior to this PR the method name was just the hash of the filename.
> Support multi-contract files w/ inheritance for solc 0.6.x

- plugins/buidler.plugin.js
#497 
Task redefinition, suggested in [497 comment][1]
[1]: https://github.com/sc-forks/solidity-coverage/issues/497#issuecomment-636236645
> Unset useLiteralContent in buidler compilation settings

- lib/parse.js
- test/integration/projects/solc-6/contracts/ContractA.sol
- test/units/buidler/standard.js
#520 
Add parsing for `TryStatement` body and its `catchClause` bodies. 
In #520 it's suggested that this structure be reported as a branch. Haven't done that here - am not sure if that's typical for other languages. However, it could be meaningful in cases where the catch block is left intentionally empty and your intent is to swallow the error. Atm an error path without statements isn't visually flagged.
> Parse TryStatements and catchClauses

- plugins/buidler.plugin.js
- plugins/resources/buidler.utils.js
- test/units/buidler/flags.js
[buidler 665][1]
Passes arg to `globby` 
These may auto-expand if `testfiles` is registered using `.addOptionalPositionalParam` (as suggested) but was not able to get this to work in tests. Don't see any glob expansion logic in the buidler `test` task - could be elsewhere though. 
[1]: https://github.com/nomiclabs/buidler/issues/665
> Expand `testfiles` arg globs

- package.json
This will fix all issues with solidity 0.7.0 crashing on start.
> Bump parser to 0.7.0

- BUIDLER_README.md
- README.md
- docs/advanced.md
- lib/api.js
- lib/injector.js
- lib/instrumenter.js
- lib/parse.js
- lib/registrar.js
- lib/validator.js
- test/units/truffle/standard.js
- test/units/validator.js
- test/util/verifiers.js
Provides a way of reducing the instrumentation footprint in a codebase by excluding measurements that most people don't find useful. 
Also shortened the instrumentation identifiers slightly.
Should resolve problem reported in [synthetix PR 732][1]
[1]: https://github.com/Synthetixio/synthetix/pull/732#issuecomment-705092226
> Make statement and function coverage measurement optional

- package.json
- test/units/truffle/standard.js
- yarn.lock
Should reduce some of the security warnings coming from `npm audit`. 
Believe truffle's still on Web3 1.2.1, so some of these (from elliptic) can't be squashed...
> Upgrade Web3 to ^1.3.0, ganache-cli to 6.11.0

- plugins/buidler.plugin.js
- test/integration/projects/solc-6/buidler.config.js
This pull request updates the Buidler plugin so it is compatible with the new compilation pipeline in Hardhat.
I think the only work left is to rename some functions and variables.
CC @alcuadrado
> [WIP] Migrate Buidler plugin to Hardhat

- README.md
We will be migrating the repository to Buidler (and Hardhat after #541 lands :slightly_smiling_face:), and I don't want this link to become broken.
> Use commit url for @openzeppelin/test-environment example

- .circleci/config.yml
- package.json
- test/units/assert.js
- test/units/function.js
- test/units/if.js
- test/units/loops.js
- test/units/statements.js
- test/units/truffle/errors.js
- test/util/util.js
- yarn.lock
It doesn't install on Node 12. 
This dep was forked as part of the initial development of 0.7.0, before a strategy to hook into any ganache version was found.
Updates CI to use Node 12 for the unit tests
> Remove ganache-core-sc dev dependency

- lib/coverage.js
- lib/injector.js
- lib/parse.js
- lib/registrar.js
- test/units/assert.js
#269 
As Nicholas Venturo notes in #269: "assert shouldn't ever fail unless the code is buggy" and it should be impossible to write test cases for both branches.
I proposed making this an option a long time ago but there does not seem to be a reason to use `assert` outside [Solidity's SMTChecker][1] or similar. Treating these as a branches discourages their use. 
(See [comments in 269][2])
[1]: https://solidity.readthedocs.io/en/v0.7.3/layout-of-source-files.html#smtchecker
[2]: https://github.com/sc-forks/solidity-coverage/issues/269#issuecomment-712897434
> Stop reporting assert statements as branches

- scripts/run-zeppelin.sh
Closes #555 
This should seamlessly become the Hardhat E2E when they go up. 
**Notes**
+ Their codecov command is exiting `0` without uploading reports (good)
+  Initially installed with yarn (ignoring the package-lock) and the test run took [twice as long][1] (20m vs 10m). Something's going on there maybe.
[1]: https://app.circleci.com/pipelines/github/sc-forks/solidity-coverage/161/workflows/adbac833-24a4-4422-9561-f041130f6ebe/jobs/2566
> Use real Zeppelin (instead of fork) as E2E

- lib/api.js
- lib/collector.js
- plugins/hardhat.plugin.js
- plugins/resources/nomiclabs.utils.js
- test/sources/js/account-one.js
- test/sources/js/account-zero.js
- test/sources/solidity/contracts/app/Simple.sol
- test/units/hardhat/standard.js
- test/util/integration.js
+ #552  Fixes bug (in HH) where `from` address is not inherited from the network config (plus tests)
+ Fixes tracing logic - the tracking was not bound to the trace step
> Set network "from" / fix trace logic

- plugins/resources/plugin.utils.js
- test/sources/solidity/contracts/app/auction.vy
- test/units/truffle/standard.js
- test/util/integration.js
#544 
Makes sure that vyper contracts also get copied into `.coverage_contracts`. They are automatically "skipped" - e.g not covered.
> Allow truffle projects to contain vyper contracts

- package.json
- plugins/hardhat.plugin.js
- plugins/resources/nomiclabs.utils.js
- scripts/run-nomiclabs.sh
- yarn.lock
#580 
#573 
Also adds an integration using (fork of) wighawags [template-ethereum-contracts][1] in order to verify everything works ok w/ hardhat-deploy.
Coverage dropped because there is hardhat version dependent logic that we check in the nomiclabs integration tests which doesn't make it to the report.
> Disable temp folder logic for hardhat >= 2.0.4

- plugins/hardhat.plugin.js
- plugins/resources/truffle.utils.js
- plugins/truffle.plugin.js
- test/units/truffle/flags.js
The logical OR tracer def triggers:
```
.coverage_contracts/Simple.sol:6:27: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
function c_true0x08454fe6(bytes32 c__0x08454fe6) public pure returns (bool){ return true; }
```
> Suppress compilation warnings introduced by injected trace statements

- plugins/resources/truffle.ui.js
- plugins/resources/truffle.utils.js
- test/units/truffle/errors.js
These were present in the 0.7.x release because Truffle exposed itself as a lib at solidity-coverage's request and it was assumed initial users might not be using the most recent versions of Truffle V5.
They can safely be removed for v0.8.x.
> Remove truffle library backup copy

- .circleci/config.yml
- package.json
- scripts/run-nomiclabs.sh
- yarn.lock
#575 
[solidity-parser/parser 34][1]
**TODO**
[1]: https://github.com/solidity-parser/parser/pull/34
> Update parser and re-enable zeppelin e2e

- lib/collector.js
- lib/coverage.js
- lib/injector.js
This should reduce the instrumentation text-size footprint a quite a bit.
> Use bytes8 instead of bytes32 as hash key

- lib/instrumenter.js
- lib/parse.js
- lib/registrar.js
- lib/validator.js
- test/units/options.js
- test/units/validator.js
- test/util/util.js
+ Adds options to toggle line and branch coverage off/on
+ Refactors option handling
This should make things slightly more efficient when:
+ generating the test matrix (which only cares about lines) 
+ instrumenting for fuzzing (which only cares about branches)
> Add coverage measurement category options

- lib/injector.js
- lib/registrar.js
- plugins/resources/plugin.utils.js
- test/sources/solidity/contracts/modifiers/reverting-fn.sol
- test/sources/solidity/contracts/modifiers/reverting-neighbor.sol
- test/units/modifiers.js
PR fixes two problems discovered running [dForceLending][1]
+ Modifier branches were not isolated from reverts downstream from them, resulting in false branch hits. New strategy is to have the post-condition as its own modifier, instead of positioning it after the `_;`
+ Matrix is not being generated correctly when only line coverage is enabled. Not certain what's going wrong here, just disabled the disabling for now since there's no obvious slowdown on a project that size.
[1]: https://github.com/dforce-network/dForceLending
> Fix pre/post strategy for modifier coverage

- lib/injector.js
- test/sources/solidity/contracts/modifiers/duplicate-mods-same-fn.sol
- test/units/modifiers.js
Fixes a bug found running Synthetix where modifiers are invoked twice in the same function header, e.g
```solidity
function exchangeEtherForSNX()
external
payable
rateNotInvalid(SNX)
rateNotInvalid(ETH)
notPaused
returns (
uint // Returns the number of SNX received
)
{
return _exchangeEtherForSNX();
}
```
PR disambiguates these using a counter.
> Allow duplicate modifiers on same function

- README.md
- lib/instrumenter.js
- lib/parse.js
- lib/registrar.js
- lib/validator.js
- test/units/modifiers.js
- test/units/validator.js
Option accepts a list of strings (simple modifier names like `nonReentrant`) to exclude from modifier branch coverage. 
This is useful for modifiers that perform non-branch preparatory work. 
Ex: `synthetix/Proxyable:optionalProxy`
```solidity
modifier optionalProxy {
_optionalProxy();
_;
}
function _optionalProxy() private {
if (Proxy(msg.sender) != proxy && Proxy(msg.sender) != integrationProxy && messageSender != msg.sender) {
messageSender = msg.sender;
}
}
```
> Add modifierWhitelist option

- README.md
- lib/abi.js
- lib/api.js
- lib/validator.js
- package.json
- plugins/resources/nomiclabs.utils.js
- plugins/resources/truffle.utils.js
- test/sources/solidity/contracts/diff/addition.sol
- test/sources/solidity/contracts/diff/events.sol
- test/sources/solidity/contracts/diff/no-change.sol
- test/sources/solidity/contracts/diff/param-change.sol
- test/sources/solidity/contracts/diff/removal.sol
- test/sources/solidity/contracts/diff/reorder.sol
- test/sources/solidity/contracts/diff/return-sig.sol
- test/sources/solidity/contracts/diff/state-mod-change.sol
- test/units/diff.js
- test/units/validator.js
- test/util/integration.js
- test/util/util.js
- yarn.lock
Core logic for a codecheck that tracks public interface changes in a PR vs. target branch.
Represented as a unified diff.
> Add ABI diff logic 

- plugins/hardhat.plugin.js
- plugins/resources/nomiclabs.ui.js
- plugins/resources/nomiclabs.utils.js
- plugins/resources/truffle.utils.js
- plugins/truffle.plugin.js
- test/units/hardhat/flags.js
- test/units/truffle/flags.js
Includes some logic fixes. Should correct coverage drop.
> Add abi diff plugin method tests

- lib/injector.js
- scripts/run-nomiclabs.sh
- test/units/assert.js
- test/units/function.js
#651, #649 
Excludes contract level instrumentation from the contract's public interface.   
This doubles the line hits for some reason...nbd - we already have this problem on the beta with the boolean hash methods.
> Use internal visibility for fn level hash method defs

- test/integration/projects/solc-8/.solcover.js
- test/integration/projects/solc-8/contracts/Contract_solc8.sol
- test/integration/projects/solc-8/hardhat.config.js
- test/integration/projects/solc-8/test/test_solc8.js
- test/units/hardhat/standard.js
#657 
Note: while line and branch coverage are correct for the new Error syntax, `revert` on it's own is not covered as a statement. Ignoring for now because statement tracking isn't supported by any of the coverage CI services.
> Add test fixture for solc-8

- README.md
- plugins/hardhat.plugin.js
> Add variable on global HH env identifying solidity-coverage task

- README.md
- docs/faq.md
- lib/api.js
- plugins/hardhat.plugin.js
- test/integration/projects/solc-8/.solcover.js
Resolves: #675, #636 to the extent possible by adding ability to custom configure solc optimizer details and some README info about this issue.
> Add solcOptimizerDetails option

- package.json
This is required to support user-defined types.
> bump @solidity-parser/parser to 0.14.0

- lib/parse.js
- package.json
- plugins/hardhat.plugin.js
- plugins/resources/nomiclabs.utils.js
- test/units/conditional.js
- test/units/function.js
- test/units/if.js
- test/units/loops.js
- test/units/modifiers.js
- test/units/options.js
- test/units/statements.js
- yarn.lock
+ Update solidity-parser/parser to 0.14.x
+ Fix ignored SIGINT in hardhat plugin
+ Configure network correctly for London HF
+ Stop tracking statement coverage for conditionals
It looks like solc 0.8.x is much stricter about what kinds of statements we're allowed to inject into conditional expressions and we can no longer track statement coverage there. 
This doesn't really matter - coveralls only displays line coverage and the branch coverage injections are unaffected.
> Fixes for beta release

- README.md
I struggled for a few hours to find where the reports were generated to, added a section that would've helped me.
> Added a section for the report location.

- package.json
This fixes a compatibility issue with Yarn strict pnpMode, as solidity-coverage calls `require()` on hardhat.
> Add hardhat to peerDependencies

- package.json
- yarn.lock
The current version of web3-utils uses the [unsafe library](https://github.com/ChainSafe/web3.js/issues/4049) `underscore`. 
Bump web-utils to its [earliest safe version](https://github.com/ChainSafe/web3.js/pull/4051).
> fix: bump web3-utils

- lib/api.js
- plugins/hardhat.plugin.js
- plugins/resources/nomiclabs.utils.js
`solidity-coverage` relies on a couple of internal APIs that we are about to change:
- The `network.provider` object is now lazily initialized, which means that you have to call `.init()` it before trying to navigate the `_wrapped` provider chain
- The `createProvider` signature changed, and this function is async now
This change means that **solidity-coverage might not work correctly with extended providers**, since we are not passing the extenders to `createProvider`. I don't think this is going to be a problem immediately, but it's something that should be fixed sooner rather than later.
> Prepare for next hardhat version

- docs/faq.md
small change than could save people some time :)
> change `.solcoverjs` occurencies to `.solcover.js`

- package.json
This description is shown e.g. when hovering with the cursor over the package name in VSCode.
This is what VSCode currently shows:
This is how it should look like:
> Add a package description

- lib/instrumenter.js
- test/sources/solidity/contracts/conditional/ternary-with-unbracketed-else.sol
- test/units/conditional.js
In #821, a ternary conditional is placed directly after an unbracketed `else` statement as below
```solidity
if (false) {} else i == 0 ? i = 0 : i--;
```
Several injections are necessary at the same location here and the order in which they happen matters. Because the branch injection for the `else` occurred first, it was being located inside the ternary clause as below
```solidity
else {
((c_8d074f5a(0x65ac343036e60c28); /*else branch */ 
i == 0 || c_false8d074f5a(0x1ca8ac37326695dd)) && c_true8d074f5a(0x909a47063763861b)) ? i = 0 : i--;}
}
```
This PR explicitly prioritizes branch injections over conditional component injections
> Perform ternary conditional injections before branch injections (#828)

- package.json
- yarn.lock
`0.16.0 --> 0.18.0`
0.17.0 fixes an associativity problem with nested ternary conditionals which might also fix #751 here.
cf: [solidity-parser/parser 99][1]
[1]: https://github.com/solidity-parser/parser/pull/99#issue-2000145254 
(Bunch of annoying integrity hash noise in the lock file, using yarn v1.7.0 here fwiw`)
> Upgrade solidity-parser to 0.18.0

- test/integration/projects/solc-8/contracts/Contract_solc8.sol
- test/integration/projects/solc-8/contracts/Library_solc8.sol
#724. This syntax might have been unsupported by `solidity-parser/parser` at some point but it seems to work without problems now.
> Add test for file level `using for` statements

- lib/parse.js
- test/integration/projects/solc-8/contracts/Abstract_solc8.sol
#766 
Updates parsing to check that modifier definitions have a body before instrumenting them (like functions)
> Fix instrumentation error for virtual modifiers

- README.md
- docs/advanced.md
- plugins/resources/plugin.ui.js
- plugins/resources/plugin.utils.js
- test/integration/projects/parallel/.solcover.js
- test/integration/projects/parallel/contracts/ContractA.sol
- test/integration/projects/parallel/hardhat.config.js
- test/units/hardhat/errors.js
Per discussion in [691 comment][1]
[1]: https://github.com/sc-forks/solidity-coverage/issues/691#issuecomment-1766476842
> Throw error when mocha parallel is set to true

- README.md
- docs/advanced.md
#610
NB: update this for v0.9.x when nyc is put in (#825)
> Document Istanbul `check-coverage` cli command

- test/sources/solidity/contracts/modifiers/postconditions.sol
- test/units/modifiers.js
Test generated for investigating #761. The modifier instrumentation does not track post-function execution in any modifiers - this test just makes sure there's nothing totally bizarre going on with Solidity's implementation under the hood.
> Add test for modifiers with post-conditions

- plugins/hardhat.plugin.js
- plugins/resources/nomiclabs.utils.js
- test/integration/projects/test-files/contracts/otherContracts/OtherContractA.sol
- test/integration/projects/test-files/test/other_contract_a.js
- test/units/hardhat/flags.js
solves #805 
The solution proposed is to add a `--sources` command option to specify the file source.
> Add command option to specify the source files to run the coverage on

- README.md
- plugins/hardhat.plugin.js
- plugins/resources/nomiclabs.utils.js
- plugins/resources/plugin.utils.js
- test/integration/projects/test-files/contracts/otherContracts/OtherContractA.sol
- test/integration/projects/test-files/test/other_contract_a.js
- test/units/hardhat/flags.js
#805 (Continuation of PR #806)
Have  
+ added the ability to specify a single source
+ made the argument relative to `paths.sources` (this differs from the the --testfiles works but is the same as `skipFiles`)
+ documented the option in the README
> Add command option to specify the source files to run the coverage on (#806)

- package.json
- scripts/ci.sh
- scripts/unit.sh
- test/units/assert.js
- test/units/conditional.js
- test/units/function.js
- test/units/if.js
- test/units/loops.js
- test/units/modifiers.js
- test/units/options.js
- test/units/or.js
- test/units/statements.js
- test/util/mochaRootHook.js
- test/util/util.js
- yarn.lock
+ Replaces ganache client with a Hardhat provider in unit tests
+ Replaces truffle-contract with ethers in unit tests
+ Removes truffle/contract depedency
In tests that revert, the hit counts have had to be adjusted downwards because truffle-contract re-executed the transaction as a `call` to fetch the revert reason.
> Use Hardhat client and ethers in unit tests

- .circleci/config.yml
The e2e tests are staying on Node 14 for the moment...they still work (and might break or require e2e target updates if changed).
> Use Node 20.11.0 in CircleCI for unit and integration tests

- plugins/hardhat.plugin.js
- test/integration/standard.js
- test/sources/projects/task-hooks/.solcover.js
- test/sources/projects/task-hooks/contracts/Hooks.sol
- test/sources/projects/task-hooks/hardhat.config.js
- test/sources/projects/task-hooks/test/hooks.js
- test/sources/projects/test-files/.solcover.js
#772 
+ Adds missing hook
+ Moves task hooks into dedicated test
(Think this was missing because of an oversight...)
> Add missing `onPreCompile` stage hook

- test/sources/projects/hardhat-compile-config/hardhat.config.js
- test/sources/projects/overrides-viaIR/hardhat.config.js
`viaIR` was at the wrong level in the hardhat.config.js for these tests. (Codecov caught this - should tick up slightly)
> Fix test project configs for viaIR detection in overrides

- test/sources/solidity/contracts/try/try-catch-empty-blocks.sol
- test/sources/solidity/contracts/try/try-error-block.sol
- test/sources/solidity/contracts/try/try-multi-block.sol
- test/sources/solidity/contracts/try/try-panic-block.sol
- test/sources/solidity/contracts/try/try-revert-block.sol
- test/units/try.js
- test/util/util.js
Prep for #852
+ Adds test files and a description of current behavior in some basic cases
> Add try / catch unit tests

- test/integration/standard.js
- test/sources/projects/file-level-functions/.solcover.js
- test/sources/projects/file-level-functions/contracts/FunctionA.sol
- test/sources/projects/file-level-functions/contracts/FunctionB.sol
- test/sources/projects/file-level-functions/contracts/UsesFunctions.sol
- test/sources/projects/file-level-functions/hardhat.config.js
- test/sources/projects/file-level-functions/test/usesFunctions.js
> Add tests for file-level function declarations

- .circleci/config.yml
- plugins/resources/nomiclabs.utils.js
- scripts/nomiclabs.sh
+ #853 
+ [hardhat issue 3961][1]
The @nomicfoundation/hardhat-foundry plugin makes `paths.sources` relative but it needs to be absolute when piping instrumented sources into the compilation jobs subtask here:
https://github.com/sc-forks/solidity-coverage/blob/7ad7288dca2b081c2ac0c085acbf2b5e9851b71a/plugins/hardhat.plugin.js#L27-L35
Also 
+ added hardhat-foundry to the nomiclabs project E2E 
+ added installation of foundry in CI 
+ run `npx hardhat init-foundry`
LGTM: 
[1]: https://github.com/NomicFoundation/hardhat/issues/3961
> Coerce sources path to absolute path if necessary

- lib/collector.js
- test/integration/standard.js
- test/sources/projects/modifiers/contracts/ModifiersD.sol
- test/sources/projects/modifiers/external/Context.sol
- test/sources/projects/modifiers/external/Ownable.sol
- test/sources/projects/modifiers/test/modifiers.js
In #854 (v0.8.7) logic was added to the collector that filters duplicate consecutive hashes because viaIR was doing that and messing up the hit counts.
However #863 reports a case where these duplicates are expected - they're inheriting onlyOwner and testing the implementation by switching the EOA e.g
```solidity
function _authorizeUpgrade(address newImplementation) internal override onlyOwner {}
```
The instrumentation looks like:
```solidity
function a() preCondition onlyOwner postCondition {}
```
...so running the failure and success case one after another gives
```shell
precondition  <-- tx #1
precondtion   <-- tx #2
postcondition
``` 
PR adds logic to make sure this filtering only happens within a single transaction (frame?) using program counter tracking.
> Fix duplicate hash logic

- lib/collector.js
- package.json
- test/util/util.js
See #870 - it looked like instrumentation was getting stripped out by viaIR, but actually some hashes are being displaced onto higher PUSHn opcodes that the collector isn't tracking. 
(There's still an unhit line in #870 however ... waiting on answer to this https://github.com/sc-forks/solidity-coverage/issues/870#issuecomment-1968232584)
> Check all PUSH opcodes for instr. hashes when viaIR is true

- .circleci/config.yml
- lib/collector.js
- scripts/zeppelin.sh
#870 
#871 redux, with SWAP this time. (This has to be it though - there's nowhere else they can vanish...) 
(Zeppelin sorting tests seem slow and had to up container size to churn through it)
> Check all SWAP opcodes for inst. hashes when viaIR is true

- lib/api.js
- lib/collector.js
- plugins/resources/nomiclabs.utils.js
- plugins/resources/plugin.utils.js
- scripts/zeppelin.sh
- test/integration/standard.js
- test/sources/projects/hardhat-compile-config/.solcover.js
- test/sources/projects/hardhat-compile-config/contracts/ContractD1.sol
- test/sources/projects/hardhat-compile-config/hardhat.config.js
- test/sources/projects/hardhat-compile-config/test/contractd1.js
- test/util/verifiers.js
#876 
solc v0.4.x locates instrumentation hashes across a wider range of opcodes than subsequent versions (similar to `viaIR`)
PR:
+ detects when v0.4.x is being used 
+ tells collector to check the expanded dictionary of opcodes if it is
> Support solc v0.4.x

- plugins/resources/plugin.utils.js
#879 
Addresses EISDIR crash reported in #879 when directory names contain a period. The `path.extName` function was returning an extension in this case causing `assembleFiles` to treat the directory as a source file.
> Use fs.stat to check directory status

- package.json
- plugins/hardhat.plugin.js
- plugins/resources/nomiclabs.ui.js
- plugins/resources/nomiclabs.utils.js
- test/integration/errors.js
- test/integration/standard.js
- test/sources/projects/viem/.solcover.js
- test/sources/projects/viem/contracts/Lock.sol
- test/sources/projects/viem/hardhat.config.js
- test/sources/projects/viem/test/lock.js
- yarn.lock
#874, #819
PR adds logic to support the `hardhat-viem` plugin. If you run the env variable set as below it will configure the hardhat network correctly in the `extendConfig` hook and skip provider redefinition at the task level. 
```
SOLIDITY_COVERAGE=true npx hardhat coverage
```
This approach is necessary because there's no way to know from within `extendConfig` whether the coverage task is actually being run and therefore no safe way to redefine the network settings.
If `viem` is defined in the hardhat environment and the network *has not* been set with the correct defaults, an error is thrown:
> Add extendConfig logic for hardhat-viem plugin

- plugins/resources/plugin.utils.js
- test/integration/errors.js
It's been a while :sweat_smile: - hope things are good on your side.
While reworking my test suite, I lost a lot of time to this peculiarity and a hard-to-spot typo on my side, so thought I'd see if there was an appetite to saving other people the bother down the line. I realise this is a breaking change though; would be happy to turn it in to a warning rather than an outright failure, if that's a concern.
> Error if --solcoverjs passed but file is nonexistent

- CHANGELOG.md
- README.md
- docs/api.md
Hello
I found and fixed several minor spelling issues.
Br, elias.
> Docs fix spelling issues

- plugins/hardhat.plugin.js
#891 
The existing logic for `extendConfig` tries to clone the user's config and apply it to the resolved HH config after updating gas values, accidentally overwriting some necessary default fields in the forking object, which looks like this:
```ts
forking: {
url: 'https://opt-mainnet.g.alchemy.com/v2/....',
enabled: true,
httpHeaders: {},
blockNumber: 123190000
},
```
This isn't necessary, the `config` object is already seeded with user's values when `extendConfig` executes.
> Stop overwriting forking config in extendConfig

- docs/matrix.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Repeated occurrences of the word `should` have been removed x13.
Please review the changes and let me know if any additional changes are needed.
> fix: typos in documentation files

- package.json
- yarn.lock
Adds custom storage layout support
https://github.com/solidity-parser/parser/releases/tag/v0.20.0
> Update solidity-parser/parser to 0.20.1
