- circle.yml
- package.json
- yarn.lock
> Add truffle as dev dep, re-yarn. 

- bin/exec.js
- test/cli.js
- test/cli/events.js
- test/cli/testrpc-options.js
- test/sources/cli/Events.sol
+ If truffle tests error, script generates coverage but exits 1.
> Add (disabled) events filter unit test

- lib/parse.js
- test/sources/statements/tuple.sol
- test/statements.js
+ Makes `VariableTupleDeclaration` parsing like `VariableDeclaration` parsing. 
+ Fixes tests
+ Resolves #49
> Fix tuple parsing / update tests

- bin/exec.js
- test/cli.js
- test/util/mockTestCommand.js
https://github.com/sc-forks/solidity-coverage/issues/66
https://travis-ci.org/gnosis/gnosis-contracts/builds/253400774
> Fix race condition

- bin/exec.js
I needed this to see this:
https://travis-ci.org/gnosis/gnosis-contracts/jobs/253611700
> More informative TestRPC failure logging

- .eslintrc
- bin/exec.js
- lib/app.js
- lib/instrumenter.js
- lib/truffleConfig.js
- test/app.js
- test/cli/sign.js
- test/conditional.js
- test/statements.js
- test/util/mockTestCommand.js
Also bumped eslint complexity rule up to 20 (default) because it didn't like seeing a dozen config assignments in the app class constructor.
> Add testrpc-sc signing test and lint

- README.md
- docs/faq.md
> Simplify and reorder README, add CI integration guide

- .gitignore
- README.md
- docs/faq.md
- lib/coverageMap.js
- lib/injector.js
- lib/instrumenter.js
- lib/parse.js
- package.json
- test/assert.js
- test/conditional.js
- test/expressions.js
- test/function.js
- test/if.js
- test/loops.js
- test/return.js
- test/sources/assert/Assert.sol
- test/sources/assert/RequireMultiline.sol
- test/sources/cli/Events.sol
- test/sources/function/multiple.sol
- test/sources/statements/compilation-error.sol
- test/statements.js
- test/util/util.js
- test/util/vm.js
- test/zeppelin.js
Three minor changes since you saw this yesterday:
* I refactored the duplicate code in `instrumenter.js`
* I clarified the comment in the chained call test that changed, which confused me for a few minutes until I realised what was happening.
* Updated the README / FAQ to explain what was with the assert/require branches.
Surprisingly, this does seem ready to merge. I thought it was going to be a lot tougher!
Closes #74
> Cover Assert/Require statements as branches

- lib/app.js
- test/app.js
> Fix lcov html report bug

- lib/app.js
> Verify testrpc-sc location in node_modules

- lib/app.js
> reads trace file line by line

- lib/app.js
- test/assert.js
- test/comments.js
- test/conditional.js
- test/expressions.js
- test/function.js
- test/if.js
- test/loops.js
- test/statements.js
> Add relative mapping logic, remove path corrections in tests

- lib/app.js
- package-lock.json
- package.json
Byzantium, also got rid of yarn/npm distinction in `app.js`
Closes #115
> testrpc-sc to 6.0.3

- lib/app.js
> Add sanity checks for contracts and coverageEnv folders

- lib/app.js
Ooops, forgot to do this to #159.
> Fix misnamed compileCommand option

- README.md
- docs/faq.md
> Update README with workaround for local truffle dep bug

- package-lock.json
- package.json
- test/sources/statements/fn-struct.sol
> Bump parser to 0.4.3

- package-lock.json
- package.json
> Bump parser 0.4.4

- lib/app.js
> Use relative mapping

- lib/preprocessor.js
- package-lock.json
- test/cli/totallyPure.js
- test/sources/cli/TotallyPure.sol
> Preserve CRs of removed modifiers

- package-lock.json
- package.json
Bump parser to 0.4.5. Brings in fixes by @vdrg that allow function types to be passed as parameters.
> Bump parser: function types as parameters to functions

- lib/instrumentSolidity.js
- lib/parse.js
- test/cli/totallyPure.js
- test/sources/cli/Face.sol
- test/sources/cli/TotallyPure.sol
- test/util/mockTruffle.js
Fixes #162.
Sneaks a test for this into the Pure/View cli test.
> Allow interface contracts

- package-lock.json
- package.json
> Bump parser: stop crashing on JS keywords

- package-lock.json
- package.json
Fixes #208 thanks to PR by @andresilva at `solidity-parser-sc`
> Update solidity-parser-sc to 0.4.7

- lib/app.js
> Cleanup stdout/stderr streams on exit

- lib/app.js
- package-lock.json
- package.json
Fixes #186  (testrpc-sc refuses to die on Linux)
Tested this in travis (Ubuntu Trusty) [here](https://travis-ci.org/cgewecke/tree-kill-test)
> Kill testrpc w/ tree-kill

- package-lock.json
- package.json
Was a version too low for the `growl` fix.
> Fix mocha version in parser

- package-lock.json
- package.json
#250 
Parse: `pragma experimental ABIEncoderV2;`
> Upgrade parser to 0.4.11 & package-lock.json

- lib/app.js
> Also copy dotfiles into env

- lib/app.js
- lib/preprocessor.js
- test/sources/statements/unbracketed-sigleton-multi.sol
add check to honor the excluded files in `view` and `pure` modifiers processing functionality.
> Honor excluded files

- lib/app.js
See: https://github.com/sc-forks/solidity-coverage/issues/131#issuecomment-417748614
> Fix issue with imported packages with subfolders

- README.md
- test/assembly.js
- test/if.js
- test/sources/if/else-if-unbracketed-multi.sol
> Add tests for instrumenting multiple unbracketed else ifs

- test/assembly.js
- test/sources/assembly/if.sol
> Add regression test for assembly if blocks

- lib/preprocessor.js
- test/if.js
- test/sources/if/if-else-no-brackets.sol
> Fix bug preprocessing unbracketed if else statements

- package.json
- yarn.lock
#378 
#369 
Not sure why the parser has an issue with the file in #378, will investigate. 0.4.7 seems like it's working though.
> Pin parser-antlr to 0.4.7 / web3 to 1.2.1

- dist/truffle.plugin.js
- package.json
- test/integration/projects/test-files/.solcover.js
- test/integration/projects/test-files/contracts/ContractA.sol
- test/integration/projects/test-files/contracts/ContractB.sol
- test/integration/projects/test-files/contracts/ContractC.sol
- test/integration/projects/test-files/contracts/Migrations.sol
- test/integration/projects/test-files/migrations/1_initial_migration.js
- test/integration/projects/test-files/migrations/2_contracta.js
- test/integration/projects/test-files/migrations/3_contractb.js
- test/integration/projects/test-files/migrations/4_contractc.js
- test/integration/projects/test-files/test/globby_b.js
- test/integration/projects/test-files/test/globby_c.js
- test/integration/projects/test-files/test/specific_a.js
- test/integration/projects/test-files/truffle-config.js
- test/units/app.js
- yarn.lock
Example:
```
npx truffle run coverage --file test/tokens/*.js
```
> Add --file command option (for test subsets)

- lib/app.js
- lib/ui.js
- test/units/truffle/errors.js
This error appears to be uncatch-able. It throws...but I can't even catch it in a test try block. Idk. 
Adding a skipped test, some comments & cleaning up the UI message previously written for this.
> Add EADDRINUSE test

- plugins/resources/plugin.utils.js
> Normalize target paths in "assembleFiles" for Windows

- plugins/buidler.plugin.js
> updated default values for buidler config

- lib/instrumenter.js
- lib/preprocessor.js
- package.json
- yarn.lock
The latest and greatest....
Fixes 
+ #493 
+ #483 
+ #481
> Use @solidity-parser/parser (^0.5.2)

- package.json
- yarn.lock
cf: [@solidity-parser/parser 14][1]
Also checked with [sc-forks/parser-testing][2] and LGTM.
[1]: https://github.com/solidity-parser/parser/issues/14#issuecomment-616651948
[2]: https://github.com/sc-forks/parser-testing
> Upgrade @solidity-parser/parser to ^0.6.0

- package.json
- plugins/resources/buidler.utils.js
- test/integration/projects/buidler-gas-reporter/buidler.config.js
- test/integration/projects/buidler-gas-reporter/contracts/ContractA.sol
- test/integration/projects/buidler-gas-reporter/test/test.js
- test/units/buidler/standard.js
- yarn.lock
> Auto disable buidler-gas-reporter

- plugins/buidler.plugin.js
> Lazy load ganache in buidler plugin

- BUIDLER_README.md
- README.md
- package.json
- scripts/run-netlify.sh
- test/integration/projects/multiple-suites/buidler.config.js
- yarn.lock
Tried to repro #491 in the tests but wasn't able to. The automatic network setting seems to work when buidlerevm is set as defaultNetwork and when it's a defined network.
Am updating the docs to recommend an explicit network configuration anyway since that's known to work.
> Update buidler dev deps & recommend using --network

- package.json
Verifying that the netlify job works...
> Bump parser to 0.7.0 (#529)

- package.json
- yarn.lock
> Upgrade solidity-parser/parser to 0.8.1

- package.json
- yarn.lock
> Upgrade @truffle/provider to 0.2.24

- plugins/hardhat.plugin.js
- plugins/resources/nomiclabs.ui.js
- test/integration/projects/hardhat-compile-config/.solcover.js
- test/integration/projects/hardhat-compile-config/contracts/ContractA1.sol
- test/integration/projects/hardhat-compile-config/contracts/ContractB1.sol
- test/integration/projects/hardhat-compile-config/contracts/ContractC1.sol
- test/integration/projects/hardhat-compile-config/hardhat.config.js
- test/integration/projects/hardhat-compile-config/test/contracta1.js
- test/integration/projects/hardhat-compile-config/test/contractb1.js
- test/integration/projects/hardhat-compile-config/test/contractc1.js
- test/units/hardhat/standard.js
#548 
Test that optimization is disabled for all compilers in a config
> Add complex compilation test case

- README.md
- lib/injector.js
- lib/instrumenter.js
- lib/parse.js
- lib/registrar.js
- lib/validator.js
- test/integration/projects/modifiers/.solcover.js
- test/integration/projects/modifiers/contracts/ModifiersA.sol
- test/integration/projects/modifiers/contracts/ModifiersB.sol
- test/integration/projects/modifiers/contracts/ModifiersC.sol
- test/integration/projects/modifiers/hardhat.config.js
- test/integration/projects/modifiers/test/modifiers.js
- test/integration/projects/modifiers/truffle-config.js
- test/sources/js/modified.js
- test/sources/solidity/contracts/app/Modified.sol
- test/sources/solidity/contracts/modifiers/both-branches.sol
- test/sources/solidity/contracts/modifiers/listed-modifiers.sol
- test/sources/solidity/contracts/modifiers/multiple-fns-same-mod.sol
- test/sources/solidity/contracts/modifiers/multiple-mods-same-fn.sol
- test/sources/solidity/contracts/modifiers/override-function.sol
- test/sources/solidity/contracts/modifiers/same-contract-fail.sol
- test/sources/solidity/contracts/modifiers/same-contract-pass.sol
- test/units/function.js
- test/units/hardhat/standard.js
- test/units/modifiers.js
- test/units/validator.js
> Add modifier-invocation-as-branch coverage

- lib/parse.js
- test/integration/projects/solc-7/contracts/Contract_solc7.sol
> Fix pragma abicoder v2 instrumentation

- plugins/hardhat.plugin.js
- plugins/resources/nomiclabs.utils.js
> Hardhat: call process.exit on SIGINT

- package.json
- yarn.lock
> Update @solidity-parser/parser to ^0.12.0

- package.json
- yarn.lock
> Update hardhat to 2.8.2

- package.json
- yarn.lock
Continuation of #689. (Also updating the yarn.lock)
> Update solidity-parser/parser to 0.14.0

- .circleci/config.yml
- package.json
- yarn.lock
Verifying that tests pass w/ latest hardhat
cf: https://github.com/sc-forks/solidity-coverage/issues/652#issuecomment-1089298787
> Update hardhat to 2.9.3

- plugins/hardhat.plugin.js
(Might speed things up a little)
> Lazy load hh plugin resources

- lib/parse.js
- test/integration/projects/solc-8/contracts/Contract_solc8.sol
- test/integration/projects/solc-8/test/test_solc8.js
- test/units/hardhat/standard.js
> Add support for `UncheckedStatement` blocks

- README.md
Formatted markdown previews weirdly, creating an additional line, deleting new line fixes it
> readme options table format fix

- package.json
- yarn.lock
> Restore web3-utils

- package.json
- yarn.lock
> Update solidity-parser to 0.16.0

- package.json
- yarn.lock
> Use ^ in mocha dep

- test/integration/projects/solc-8/contracts/Contract_solc8.sol
- test/integration/projects/solc-8/hardhat.config.js
> Test named mapping keys Solidity syntax

- FUNDING.json
> Add drips funding config

- docs/faq.md
Related to #715 
Explanation Comment: https://github.com/sc-forks/solidity-coverage/issues/715#issuecomment-1840433695
> Update faq.md with another workaround

- test/integration/standard.js
- test/sources/projects/hardhat-mine/.solcover.js
- test/sources/projects/hardhat-mine/contracts/Setter.sol
- test/sources/projects/hardhat-mine/hardhat.config.js
- test/sources/projects/hardhat-mine/test/testMine.js
#707
Adds a test for error reported in #707. This seems to have been resolved at hardhat.
> Add test for transaction price errors with hardhat_mine

- README.md
This completes one task in #844 as the heading suggests.
> [#844] Removed Contributor Section from README.md
